"""migration_3

Revision ID: 19dfbe9f6e54
Revises: c701633cd5c5
Create Date: 2024-07-24 14:11:45.006570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dfbe9f6e54'
down_revision: Union[str, None] = 'c701633cd5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade', 'numb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('numb', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
