"""Delete product grade

Revision ID: 9cdd057b2e9e
Revises: 9be28b9816e0
Create Date: 2024-08-15 14:15:58.553343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdd057b2e9e'
down_revision: Union[str, None] = '9be28b9816e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_grade_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'grade_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('grade_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_grade_id_fkey', 'products', 'grade', ['grade_id'], ['id'])
    # ### end Alembic commands ###
