"""migration_2

Revision ID: c701633cd5c5
Revises: 6e9e1c6ca6fb
Create Date: 2024-07-24 14:08:45.759990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c701633cd5c5'
down_revision: Union[str, None] = '6e9e1c6ca6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('numb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade', 'numb')
    # ### end Alembic commands ###
