"""Delete product grade

Revision ID: d783b3ef7e0f
Revises: 9cdd057b2e9e
Create Date: 2024-08-15 14:17:32.223343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd783b3ef7e0f'
down_revision: Union[str, None] = '9cdd057b2e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
