version: '3'
services:
  app:
    image: market_sprint
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - PYTHONPATH=/usr/src/market_place_sprint
      - DATABASE_URL=postgres://user:password@postgres:5432/mydatabase
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15673:15672"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
