version: '3.8'
services:
  app:
    image: market_sprint
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - PYTHONPATH=/usr/src/market_place_sprint
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - "15672:15672"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: market_place_sprint_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22552552000
    ports:
      - "5432:5432"